revisions v2
stac-extensions/classification pull request #15
Opened 2022-03-22 16:32 UTC by drwelby

PR for comments @m-mohr @pjhartzell

2022-03-22 17:31 UTC, pjhartzell commented on README.md
> +A Bit Field stores classes within a range of bits in a data value. The range is described by the offest of the first bit from the rightmost position, and the length of bits used to store the class va
minor typo: change offest to offset

2022-03-22 17:38 UTC, pjhartzell requested changes
README revisions and additions look good! I noted one minor typo.

2022-03-22 17:48 UTC, pjhartzell commented
With respect to number #9, should we update `value` in the Class Object to something like `number|[number]|Range Object`? 

Range Object being the same as in the Collection specification: https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#range-object

2022-03-22 18:05 UTC, drwelby commented
I am horribly inconsistent about using periods in lists so I will get the formatting standardized at some point.

2022-03-24 18:38 UTC, drwelby commented
closing, see latest PR

2022-03-24 18:38 UTC, closed without merging